# Generated by Django 2.0.7 on 2018-07-30 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='watchedlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='watchedlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Bengali', 'Bengali')], default='English', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.URLField(default='https://notfound.com/notfound.html'),
        ),
        migrations.AddField(
            model_name='item',
            name='platform',
            field=models.CharField(choices=[('Youtube', 'Youtube'), ('Netflix', 'Netflix'), ('Hoichoi', 'Hoichoi')], default='Youtube', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='genre',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Action', 'Action'), ('Sci-Fi', 'Sci-Fi')], max_length=50),
        ),
        migrations.DeleteModel(
            name='watchedlist',
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdb.item'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
