# Generated by Django 2.0.7 on 2018-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0002_auto_20180730_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover',
            field=models.ImageField(upload_to='static/covers/'),
        ),
    ]
