# Generated by Django 2.0.7 on 2018-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0003_auto_20180730_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cover',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
