# Generated by Django 2.1 on 2018-08-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0008_auto_20180803_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
