# Generated by Django 2.1 on 2018-08-04 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0010_auto_20180804_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmodel',
            name='itempk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdb.ItemModel'),
        ),
    ]
