# Generated by Django 2.1 on 2018-08-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdb', '0011_auto_20180804_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingmodel',
            old_name='itempk',
            new_name='item',
        ),
    ]
